### ISSUE TITLE
.well-known endpoint should account for using non-default ports

### ISSUE THREAD

**Issue by ssabpisa** [OADA/oada-ref-auth-js#17]
Set PORT to 8443.
`export PORT=8443`
then start the server with default config
`node index.js`
visit the well-known endpoint
the returned endpoints do not account for the non-default port value.

**Comment by ssabpisa** [comment]
Should this be opened in https://github.com/OADA/well-known-json-js instead?

**Comment by awlayton** [comment]
I don't think so. I believe this is a result of how it is being used, not how it is written.

**Comment by awlayton** [comment]
Actually maybe it is a bug in that module...

**Comment by awlayton** [comment]
@ssabpisa Are all the endpoints in `.well-known/oada-configuration` wrong for you, or just `"oada_base_uri"`?

I got one like this when I tried:
```JSON
{
  "authorization_endpoint": "http://localhost:3000/auth",
  "token_endpoint": "http://localhost:3000/token",
  "oada_base_uri": "http://identity.oada-dev.com",
  "client_secret_alg_supported": [
    "RS256"
  ]
}
```

**Comment by ssabpisa** [comment]
My bad. I didnt check but it seems correct. The problem must be somewhere else

**Comment by awlayton** [comment]
Well `"oada_base_uri"` still doesn't have the port. Could that have caused the error you saw?

**Comment by ssabpisa** [comment]
I dont think so.

**Comment by awlayton** [comment]
I think the problem is the ID token has the wrong issuer (token endpoint **without** port), but the well-known document has the right one (token endpoint **with** port).

Doesn't your code compare the two?

**Comment by ssabpisa** [comment]
I think the test used the right one (with port), I checked it using jwt.io

**Comment by abalmos** [comment]
`oada_base_uri` is the path to the actual OADA API. It is not connected with the URLs that are used for auth.

Right now it comes directly from `config.js` but we have talked about moving it to its own .well-known endpoint. @awlayton do you recall the names we picked?

**Comment by abalmos** [comment]
Maybe it was leave `oada_base_uri` in `./well-known/oada-configuration` and move the other keys to `.well-known/oauth2-configuration`?

**Comment by awlayton** [comment]
Yeah it was something like the second thing.
