### ISSUE TITLE
Require X-Frame-Options?

### ISSUE THREAD

**Issue by abalmos** [OADA/oada-ref-auth-js#22]
Maybe we should require the use of "X-Frame-Options" in OADA auth^2?
http://www.bubblecode.net/en/2013/03/10/understanding-oauth2/#Clickjacking

https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options

**Comment by aultac** [comment]
Sounds like that would be prudent.

Aaron

**Comment by awlayton** [comment]
Seems like a good thing to do.

**Comment by aultac** [comment]
At some point it would be reasonable to ask why in the world the default behavior would be the insecure one where you can overlay transparent click regions over someone else's webpage BY DEFAULT and you have to explicitly ask for that not to be done if you don't want it?  I guess that will be one of the mysteries of the universe.....

Aaron
